content:
  - name: domain
    label: Domain
    path: src/content/domain
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true